---
abstract: 'Setting and Passing test variables.'
author:
  - 'Toru Yamaguchi <zigorou@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Path: 0
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Install-TestVars
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  Getopt::Long: 0
  Module::Install: 0
  Module::Install::Base: 0
  Term::ReadLine: 0
  Term::UI: 0
  Text::ASCIITable: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_02
